import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'hsl(var(--primary))',
        'primary-deep': 'hsl(var(--primary-deep))',
        'primary-press': 'hsl(var(--primary-press))',
        'primary-soft': 'hsl(var(--primary-soft))',
        'brand-dark': 'hsl(var(--brand-dark-900))',
        ink: 'hsl(var(--ink))',
        'ink-secondary': 'hsl(var(--ink-secondary))',
        'ink-mute': 'hsl(var(--ink-mute))',
        canvas: 'hsl(var(--canvas))',
        'canvas-soft': 'hsl(var(--canvas-soft))',
        'canvas-cream': 'hsl(var(--canvas-cream))',
        hairline: 'hsl(var(--hairline))',
        'hairline-input': 'hsl(var(--hairline-input))',
        ruby: 'hsl(var(--ruby))',
        magenta: 'hsl(var(--magenta))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        pill: '9999px',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        huge: '64px',
      },
      fontSize: {
        'display-xxl': ['56px', { lineHeight: '1.03', letterSpacing: '-1.4px', fontWeight: '300' }],
        'display-xl': ['48px', { lineHeight: '1.15', letterSpacing: '-0.96px', fontWeight: '300' }],
        'display-lg': ['32px', { lineHeight: '1.1', letterSpacing: '-0.64px', fontWeight: '300' }],
        'display-md': ['26px', { lineHeight: '1.12', letterSpacing: '-0.26px', fontWeight: '300' }],
        'heading-lg': ['22px', { lineHeight: '1.1', letterSpacing: '-0.22px', fontWeight: '300' }],
        'heading-md': ['20px', { lineHeight: '1.4', letterSpacing: '-0.2px', fontWeight: '300' }],
        'heading-sm': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '300' }],
        'body-lg': ['16px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '300' }],
        'body-md': ['15px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '300' }],
        'body-tabular': ['14px', { lineHeight: '1.4', letterSpacing: '-0.42px', fontWeight: '300', fontFeatureSettings: 'tnum' }],
        'button-md': ['16px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '400' }],
        'button-sm': ['14px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.4', letterSpacing: '-0.39px', fontWeight: '400' }],
        micro: ['11px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '300' }],
        'micro-cap': ['10px', { lineHeight: '1.15', letterSpacing: '0.1px', fontWeight: '400', textTransform: 'uppercase' }],
      },
      boxShadow: {
        'stripi-sm': 'rgba(0, 55, 112, 0.08) 0 1px 3px',
        'stripi-md': 'rgba(0, 55, 112, 0.08) 0 8px 24px, rgba(0, 55, 112, 0.04) 0 2px 6px',
      },
    },
  },
  plugins: [],
};

export default config;
