import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'hsl(var(--primary) / <alpha-value>)',
        'primary-deep': 'hsl(var(--primary-deep) / <alpha-value>)',
        'primary-press': 'hsl(var(--primary-press) / <alpha-value>)',
        'primary-soft': 'hsl(var(--primary-soft) / <alpha-value>)',
        'brand-dark': 'hsl(var(--brand-dark-900) / <alpha-value>)',
        ink: 'hsl(var(--ink) / <alpha-value>)',
        'ink-secondary': 'hsl(var(--ink-secondary) / <alpha-value>)',
        'ink-mute': 'hsl(var(--ink-mute) / <alpha-value>)',
        canvas: 'hsl(var(--canvas) / <alpha-value>)',
        'canvas-soft': 'hsl(var(--canvas-soft) / <alpha-value>)',
        'canvas-cream': 'hsl(var(--canvas-cream) / <alpha-value>)',
        hairline: 'hsl(var(--hairline) / <alpha-value>)',
        'hairline-input': 'hsl(var(--hairline-input) / <alpha-value>)',
        ruby: 'hsl(var(--ruby) / <alpha-value>)',
        magenta: 'hsl(var(--magenta) / <alpha-value>)',
        background: 'hsl(var(--background) / <alpha-value>)',
        foreground: 'hsl(var(--foreground) / <alpha-value>)',
        card: 'hsl(var(--card) / <alpha-value>)',
        'card-foreground': 'hsl(var(--card-foreground) / <alpha-value>)',
        popover: 'hsl(var(--popover) / <alpha-value>)',
        'popover-foreground': 'hsl(var(--popover-foreground) / <alpha-value>)',
        muted: 'hsl(var(--muted) / <alpha-value>)',
        'muted-foreground': 'hsl(var(--muted-foreground) / <alpha-value>)',
        accent: 'hsl(var(--accent) / <alpha-value>)',
        'accent-foreground': 'hsl(var(--accent-foreground) / <alpha-value>)',
        destructive: 'hsl(var(--destructive) / <alpha-value>)',
        'destructive-foreground': 'hsl(var(--destructive-foreground) / <alpha-value>)',
        border: 'hsl(var(--border) / <alpha-value>)',
        input: 'hsl(var(--input) / <alpha-value>)',
        ring: 'hsl(var(--ring) / <alpha-value>)',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        pill: '9999px',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '32px',
        huge: '64px',
      },
      fontSize: {
        'display-xxl': ['56px', { lineHeight: '1.03', letterSpacing: '-1.4px', fontWeight: '300' }],
        'display-xl': ['48px', { lineHeight: '1.15', letterSpacing: '-0.96px', fontWeight: '300' }],
        'display-lg': ['32px', { lineHeight: '1.1', letterSpacing: '-0.64px', fontWeight: '300' }],
        'display-md': ['26px', { lineHeight: '1.12', letterSpacing: '-0.26px', fontWeight: '300' }],
        'heading-lg': ['22px', { lineHeight: '1.1', letterSpacing: '-0.22px', fontWeight: '300' }],
        'heading-md': ['20px', { lineHeight: '1.4', letterSpacing: '-0.2px', fontWeight: '300' }],
        'heading-sm': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '300' }],
        'body-lg': ['16px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '300' }],
        'body-md': ['15px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '300' }],
        'body-tabular': ['14px', { lineHeight: '1.4', letterSpacing: '-0.42px', fontWeight: '300', fontFeatureSettings: 'tnum' }],
        'button-md': ['16px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '400' }],
        'button-sm': ['14px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.4', letterSpacing: '-0.39px', fontWeight: '400' }],
        micro: ['11px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '300' }],
        'micro-cap': ['10px', { lineHeight: '1.15', letterSpacing: '0.1px', fontWeight: '400', textTransform: 'uppercase' }],
      },
      boxShadow: {
        'stripi-sm': 'rgba(0, 55, 112, 0.08) 0 1px 3px',
        'stripi-md': 'rgba(0, 55, 112, 0.08) 0 8px 24px, rgba(0, 55, 112, 0.04) 0 2px 6px',
      },
    },
  },
  plugins: [],
};

export default config;
