import { Employee, Department, Shift, AttendanceRecord, AttendanceRequest, Company } from './types'

export const mockEmployees: Employee[] = [
  {
    id: '1',
    fullName: 'Nguyễn Minh Anh',
    employeeCode: 'NV001',
    email: 'minh.anh@timeflow.com',
    phone: '0901234567',
    dateOfBirth: '1990-03-15',
    gender: 'female',
    departmentId: '1',
    position: 'Senior Developer',
    contractType: 'full-time',
    startDate: '2022-01-15',
    defaultShiftId: '1',
    workLocation: 'Văn phòng chính',
    status: 'active',
    allowPayslipView: true,
    allowRemoteCheckIn: true,
    systemRole: 'manager',
    createdAt: '2022-01-15',
  },
  {
    id: '2',
    fullName: 'Trần Hoàng Nam',
    employeeCode: 'NV002',
    email: 'hoang.nam@timeflow.com',
    phone: '0912345678',
    dateOfBirth: '1992-07-20',
    gender: 'male',
    departmentId: '1',
    position: 'Developer',
    contractType: 'full-time',
    startDate: '2022-06-01',
    defaultShiftId: '1',
    workLocation: 'Văn phòng chính',
    status: 'active',
    allowPayslipView: true,
    allowRemoteCheckIn: false,
    systemRole: 'employee',
    createdAt: '2022-06-01',
  },
  {
    id: '3',
    fullName: 'Lê Thu Hương',
    employeeCode: 'NV003',
    email: 'thu.huong@timeflow.com',
    phone: '0923456789',
    dateOfBirth: '1995-11-08',
    gender: 'female',
    departmentId: '2',
    position: 'HR Manager',
    contractType: 'full-time',
    startDate: '2021-02-10',
    defaultShiftId: '1',
    workLocation: 'Văn phòng chính',
    status: 'active',
    allowPayslipView: true,
    allowRemoteCheckIn: true,
    systemRole: 'manager',
    createdAt: '2021-02-10',
  },
  {
    id: '4',
    fullName: 'Phạm Quốc Khánh',
    employeeCode: 'NV004',
    email: 'quoc.khanh@timeflow.com',
    phone: '0934567890',
    dateOfBirth: '1988-05-12',
    gender: 'male',
    departmentId: '3',
    position: 'Accountant',
    contractType: 'full-time',
    startDate: '2020-08-15',
    defaultShiftId: '1',
    workLocation: 'Văn phòng chính',
    status: 'active',
    allowPayslipView: false,
    allowRemoteCheckIn: false,
    systemRole: 'employee',
    createdAt: '2020-08-15',
  },
  {
    id: '5',
    fullName: 'Vũ Ngọc Mai',
    employeeCode: 'NV005',
    email: 'ngoc.mai@timeflow.com',
    phone: '0945678901',
    dateOfBirth: '1998-09-22',
    gender: 'female',
    departmentId: '4',
    position: 'Logistics Officer',
    contractType: 'full-time',
    startDate: '2023-01-10',
    defaultShiftId: '2',
    workLocation: 'Chi nhánh TP. HCM',
    status: 'active',
    allowPayslipView: true,
    allowRemoteCheckIn: false,
    systemRole: 'employee',
    createdAt: '2023-01-10',
  },
  {
    id: '6',
    fullName: 'Đỗ Văn Thành',
    employeeCode: 'NV006',
    email: 'van.thanh@timeflow.com',
    phone: '0956789012',
    dateOfBirth: '1993-12-03',
    gender: 'male',
    departmentId: '5',
    position: 'Production Manager',
    contractType: 'full-time',
    startDate: '2021-05-20',
    defaultShiftId: '3',
    workLocation: 'Nhà máy',
    status: 'active',
    allowPayslipView: true,
    allowRemoteCheckIn: false,
    systemRole: 'manager',
    createdAt: '2021-05-20',
  },
  {
    id: '7',
    fullName: 'Ngô Thị Linh',
    employeeCode: 'NV007',
    email: 'thi.linh@timeflow.com',
    phone: '0967890123',
    dateOfBirth: '1996-02-14',
    gender: 'female',
    departmentId: '1',
    position: 'QA Engineer',
    contractType: 'full-time',
    startDate: '2022-09-01',
    defaultShiftId: '1',
    workLocation: 'Văn phòng chính',
    status: 'active',
    allowPayslipView: true,
    allowRemoteCheckIn: true,
    systemRole: 'employee',
    createdAt: '2022-09-01',
  },
  {
    id: '8',
    fullName: 'Hoàng Minh Đức',
    employeeCode: 'NV008',
    email: 'minh.duc@timeflow.com',
    phone: '0978901234',
    dateOfBirth: '1991-06-25',
    gender: 'male',
    departmentId: '2',
    position: 'Recruitment Specialist',
    contractType: 'full-time',
    startDate: '2022-03-15',
    defaultShiftId: '1',
    workLocation: 'Văn phòng chính',
    status: 'on-leave',
    allowPayslipView: true,
    allowRemoteCheckIn: true,
    systemRole: 'employee',
    createdAt: '2022-03-15',
  },
  {
    id: '9',
    fullName: 'Trương Thị Hà Trang',
    employeeCode: 'NV009',
    email: 'ha.trang@timeflow.com',
    phone: '0989012345',
    dateOfBirth: '1997-08-10',
    gender: 'female',
    departmentId: '2',
    position: 'Training Officer',
    contractType: 'part-time',
    startDate: '2023-06-01',
    defaultShiftId: '2',
    workLocation: 'Văn phòng chính',
    status: 'active',
    allowPayslipView: false,
    allowRemoteCheckIn: false,
    systemRole: 'employee',
    createdAt: '2023-06-01',
  },
  {
    id: '10',
    fullName: 'Võ Hoàng Anh',
    employeeCode: 'NV010',
    email: 'hoang.anh@timeflow.com',
    phone: '0990123456',
    dateOfBirth: '1989-01-17',
    gender: 'male',
    departmentId: '3',
    position: 'Finance Manager',
    contractType: 'full-time',
    startDate: '2019-11-01',
    defaultShiftId: '1',
    workLocation: 'Văn phòng chính',
    status: 'active',
    allowPayslipView: true,
    allowRemoteCheckIn: false,
    systemRole: 'manager',
    createdAt: '2019-11-01',
  },
]

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: 'Công nghệ',
    managerId: '1',
    employeeCount: 8,
    status: 'active',
  },
  {
    id: '2',
    name: 'Nhân sự',
    managerId: '3',
    employeeCount: 4,
    status: 'active',
  },
  {
    id: '3',
    name: 'Kế toán',
    managerId: '10',
    employeeCount: 5,
    status: 'active',
  },
  {
    id: '4',
    name: 'Kho vận',
    managerId: undefined,
    employeeCount: 3,
    status: 'active',
  },
  {
    id: '5',
    name: 'Sản xuất',
    managerId: '6',
    employeeCount: 3,
    status: 'active',
  },
]

export const mockShifts: Shift[] = [
  {
    id: '1',
    name: 'Ca hành chính',
    code: 'SHIFT001',
    startTime: '08:00',
    endTime: '17:30',
    breakDuration: 90,
    lateAllowance: 5,
    workDays: [1, 2, 3, 4, 5],
    isOvernight: false,
    assignedEmployeeCount: 15,
  },
  {
    id: '2',
    name: 'Ca sáng',
    code: 'SHIFT002',
    startTime: '06:00',
    endTime: '14:00',
    breakDuration: 30,
    lateAllowance: 5,
    workDays: [1, 2, 3, 4, 5],
    isOvernight: false,
    assignedEmployeeCount: 8,
  },
  {
    id: '3',
    name: 'Ca chiều',
    code: 'SHIFT003',
    startTime: '14:00',
    endTime: '22:00',
    breakDuration: 30,
    lateAllowance: 5,
    workDays: [1, 2, 3, 4, 5],
    isOvernight: false,
    assignedEmployeeCount: 5,
  },
  {
    id: '4',
    name: 'Ca đêm',
    code: 'SHIFT004',
    startTime: '22:00',
    endTime: '06:00',
    breakDuration: 45,
    lateAllowance: 10,
    workDays: [1, 2, 3, 4, 5],
    isOvernight: true,
    assignedEmployeeCount: 0,
  },
]

export const mockAttendanceRecords: AttendanceRecord[] = [
  {
    id: '1',
    employeeId: '1',
    date: '2026-07-27',
    checkInTime: '07:58',
    checkOutTime: '17:32',
    status: 'on-time',
    location: 'Văn phòng chính',
    shiftId: '1',
  },
  {
    id: '2',
    employeeId: '2',
    date: '2026-07-27',
    checkInTime: '08:12',
    checkOutTime: '17:45',
    status: 'late',
    location: 'Văn phòng chính',
    shiftId: '1',
  },
  {
    id: '3',
    employeeId: '3',
    date: '2026-07-27',
    checkInTime: '08:05',
    status: 'on-time',
    location: 'Văn phòng chính',
    shiftId: '1',
  },
  {
    id: '4',
    employeeId: '4',
    date: '2026-07-27',
    checkInTime: '13:30',
    checkOutTime: '17:30',
    status: 'on-time',
    location: 'Văn phòng chính',
    shiftId: '1',
  },
  {
    id: '5',
    employeeId: '5',
    date: '2026-07-27',
    status: 'leave',
    shiftId: '2',
  },
  {
    id: '6',
    employeeId: '6',
    date: '2026-07-27',
    status: 'absence',
    shiftId: '3',
  },
]

export const mockRequests: AttendanceRequest[] = [
  {
    id: '1',
    employeeId: '2',
    type: 'leave',
    startDate: '2026-07-28',
    endDate: '2026-07-30',
    reason: 'Xin nghỉ phép cá nhân',
    status: 'pending',
    createdAt: '2026-07-26',
    updatedAt: '2026-07-26',
  },
  {
    id: '2',
    employeeId: '5',
    type: 'attendance-correction',
    startDate: '2026-07-27',
    startTime: '07:45',
    reason: 'Quên chấm công buổi sáng',
    status: 'pending',
    createdAt: '2026-07-27',
    updatedAt: '2026-07-27',
  },
  {
    id: '3',
    employeeId: '4',
    type: 'time-adjustment',
    startDate: '2026-07-27',
    startTime: '13:25',
    endTime: '13:35',
    reason: 'Đến sớm hơn do có cuộc họp',
    status: 'pending',
    createdAt: '2026-07-27',
    updatedAt: '2026-07-27',
  },
  {
    id: '4',
    employeeId: '7',
    type: 'leave',
    startDate: '2026-08-01',
    endDate: '2026-08-05',
    reason: 'Xin nghỉ phép hàng năm',
    status: 'approved',
    approverNote: 'Được phép',
    createdAt: '2026-07-25',
    updatedAt: '2026-07-26',
  },
  {
    id: '5',
    employeeId: '8',
    type: 'leave',
    startDate: '2026-07-27',
    endDate: '2026-07-30',
    reason: 'Xin phép bệnh',
    status: 'approved',
    approverNote: 'Nghỉ bệnh được duyệt',
    createdAt: '2026-07-27',
    updatedAt: '2026-07-27',
  },
  {
    id: '6',
    employeeId: '6',
    type: 'attendance-correction',
    startDate: '2026-07-24',
    startTime: '22:00',
    endTime: '06:00',
    reason: 'Bổ sung chấm công',
    status: 'rejected',
    approverNote: 'Không đủ thông tin',
    createdAt: '2026-07-25',
    updatedAt: '2026-07-25',
  },
]

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'Công ty Công Anh',
    code: 'CA001',
    industry: 'Công nghệ',
    employeeScale: '101-500',
    phone: '(28) 1234-5678',
    address: '123 Nguyễn Huệ, Q.1, TP. HCM',
    userRole: 'Chủ doanh nghiệp',
    employeeCount: 28,
    lastAccessed: '2026-07-26',
  },
  {
    id: '2',
    name: 'Công ty Thương mại Minh Phát',
    code: 'MP001',
    industry: 'Bán lẻ',
    employeeScale: '101-500',
    phone: '(28) 8765-4321',
    address: '456 Trần Hưng Đạo, Q.5, TP. HCM',
    userRole: 'Quản trị nhân sự',
    employeeCount: 116,
    lastAccessed: '2026-07-20',
  },
]
